name: Build and Release with JReleaser

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew clean assemble

      - name: Set up JReleaser
        uses: jreleaser/release-action@v2
        with:
          version: latest

      - name: Run JReleaser full release
        run: jreleaser full-release --stacktrace
        env:
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.SIGNING_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.SIGNING_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}
          JRELEASER_PROJECT_VERSION: ${{ github.ref_name }}
          JRELEASER_SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          JRELEASER_SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*-all.jar
