name: Publish to Maven Central

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Import GPG key securely
        run: |
          mkdir -p $HOME/.gnupg
          chmod 700 $HOME/.gnupg

          cat > private.key <<EOF
${SIGNING_KEY}
EOF

          gpg --batch --yes --import private.key

          gpg --batch --yes --armor --pinentry-mode loopback \
              --passphrase "$SIGNING_PASSWORD" \
              --export-secret-keys "$SIGNING_KEY_ID" > secring.gpg

          rm private.key
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

      - name: Publish to Maven Central
        run: |
          ./gradlew publish \
            -Psigning.keyId=${SIGNING_KEY_ID} \
            -Psigning.password=${SIGNING_PASSWORD} \
            -Psigning.secretKeyRingFile=secring.gpg \
            --no-daemon
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
